package bsl.co.ke.kephis.Pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1




/**
 * County generated by hbm2java
 */

public class County  implements java.io.Serializable {


     private String countyId;
     private String countyName;


	public String getCountyId() {
		return countyId;
	}

	public void setCountyId(String countyId) {
		this.countyId = countyId;
	}

	/**


	/**
	 * @return the countyName
	 */
	public String getCountyName() {
		return countyName;
	}

	/**
	 * @param countyName the countyName to set
	 */
	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	/**
	 * @return the countyDesc
	 */



	public String toString()
	{
		return( countyName  );
	}
    



}


